export const options = {
  EMPTY_PARAM: 'URL Params missing!',
  MISSING_BODY: 'Something is missing from the body.',
  QUERY_ERROR: 'Something went wrong while querying database.',
  NOT_FOUND: 'Query was unable to be fufilled. Item was not found.',
  ADD_ERROR: 'Something went wrong while adding data to database.',
  UPDATE_ERROR: 'Something went wrong while updating data in database.',
  DELETE_ERROR: 'Something went wrong while deleting object in database.',
  QUERY_SUCCESS: 'Query Successful!',
  ADD_SUCCESS: 'Insertion Successful!',
  UPDATE_SUCCESS: 'Update Successful!',
  DELETE_SUCCESS: 'Deletion Successful!',
  LOGIN_SUCCESS: 'Login Successful!',
  LOGIN_FAILED: 'Login Failed',
  REGISTER_SUCCESS: 'Register Success',
  REGISTER_FAILED: 'Register Failed',
  NO_TOKEN: 'No Token Provided',
  INVALID_TOKEN: 'Token is invalid',
  NO_AUTH: 'User not authorized to access this asset.',
}
